solver:
  cifar10_train_qil

data:
 num_workers: 4
 pin_memory: False
 data_path: ./data/cifar10/

model:
  name: 'resnet20'
  params:
    num_classes: 10
  pretrain:
    pretrained: False
    dir: './models/cifar10_fp.pth'
  quant_func: "QILConv2d"
  quant_params:
    bits: 8
    quant_wgt: True
    wgt_qtype: "qint"
    wgt_per_channel: False
    quant_act: True
    act_qtype: "quint"
    quant: True
    observer: True
    learning: True
    observer_step: 1960  # 10 epoch 时设置为 1960

train:
  dir: "./output"
  batch_size: 256
  num_epochs: 150
  model_dir: '_qil_W8A8'
  save_model_frequency: 1

eval:
  batch_size: 100

scheduler:
  name: 'cosine'
  params:
    T_max: 400
    eta_min: 0

optimizer:
  name: sgd
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

loss:
  name: 'cross_entropy'
  params:
    reduction: 'mean'

gpu: 0
